Repository wecode-bootcamp-korea/17-1st-Dienstag-frontend, pull requests merged in 2021-02, with the labels that each got.

#1 [17기 강민지] 메인 레이아웃 구성 및 스크롤기능 및 nav모달 구현
  package-lock.json
  package.json
  public/Data/mainCategoryData.json
  public/Data/mainStoriesData.json
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavHeadLogos.js
  src/Components/Nav/NavModal.js
  src/Components/Nav/imageList.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainCategory.js
  src/Pages/Main/MainDiy.js
  src/Pages/Main/MainStories.js
  src/Styles/common.scss
  src/index.js
Labels: Status: Accepted

#2 [17기 변미현]로그인 유효성 검사 기능 수정, 회원가입 기능 구현, 리뷰반명 완료
  package-lock.json
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavModal.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/Signup.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#3 [17기 강민지] Feature/shop 페이지 기본구성 및 기능 완료
  public/Data/backpackdata.json
  public/Data/bagDetailboxdata.json
  public/Data/mainCategoryData.json
  public/Data/recommendAcc.json
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavHeadLogos.js
  src/Components/Nav/NavModal.js
  src/Pages/Filter/FilterView.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Shop/BackpackList.js
  src/Pages/Shop/BackpackListBox.js
  src/Pages/Shop/BackpackListbox.scss
  src/Pages/Shop/BagCategoryView.js
  src/Pages/Shop/BagCategoryView.scss
  src/Pages/Shop/BagViewListBox.js
  src/Pages/Shop/ListDetail.js
  src/Pages/Shop/ListDetail.scss
  src/Pages/Shop/RecommendAcc.js
  src/Pages/Shop/RecommendAcc.scss
  src/Pages/Shop/Shop.scss
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#5 [17기 변미현] nav바에 담긴 카트 구현.
  src/Components/Nav/Nav.js
  src/Components/Nav/NavHeadLogos.js
  src/Pages/Cart/CartView.js
  src/Pages/Cart/CartView.scss
  src/Pages/Cart/CartViewItem.js
  src/Pages/Cart/CartViewItem.scss
  src/Pages/Filter/FilterView.js
  src/context.js
  src/index.js
Labels: Status: Accepted

#4 [17기 변미현] 백엔드와 통신하기 위한 fetch 함수 작성 로그인와 회원가입
  src/Pages/Login/Login.js
  src/Pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#6 [17기 변미현] 리팩토링 완료. 컨플릭트 해결!
  .prettierrc
  package-lock.json
  package.json
  src/Components/Nav/NavHeadLogos.js
  src/Components/Nav/NavModal.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/CartItem.js
  src/Pages/Cart/CartItem.scss
  src/Pages/Cart/CartView.js
  src/Pages/Cart/CartView.scss
  src/Pages/Cart/CartViewItem.js
  src/Pages/Cart/CartViewItem.scss
  src/Pages/Cart/Checkout.js
  src/Pages/Cart/Checkout.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Shop/BackpackList.js
  src/Pages/Shop/BackpackListbox.scss
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/context.js
  src/index.js
Labels: Status: 컨플릭트 해결 요청
